INSERT INTO services (name, price) VALUES
                                       ('Change filter', 25),
                                       ('Oil change', 50),
                                       ('Brake pad replacement', 100),
                                       ('Tire rotation', 35),
                                       ('Air conditioning recharge', 75),
                                       ('Transmission flush', 150),
                                       ('Battery replacement', 125),
                                       ('Windshield wiper replacement', 20),
                                       ('Coolant flush', 80),
                                       ('Fuel injector cleaning', 100),
                                       ('Engine tune-up', 200),
                                       ('Headlight restoration', 50),
                                       ('Alternator replacement', 175),
                                       ('Ignition system repair', 150),
                                       ('Suspension repair', 250),
                                       ('Power steering fluid flush', 100),
                                       ('Serpentine belt replacement', 75),
                                       ('Spark plug replacement', 75),
                                       ('Exhaust system repair', 200),
                                       ('Wheel alignment', 80);